import { useState, useEffect } from 'react';
import { API_URL } from '../config';

interface Timeline {
  id: number;
  year: number | null;
  month: number | null;
  event_title: string;
  event_description: string;
  edited_content: string;
  turning_point: string;
  created_at: string;
  is_auto_generated: number;
}

interface Photo {
  id: number;
  file_path: string;
  description: string;
}

interface User {
  id: number;
  name: string;
  age: number;
}

export default function CorrectedTextPage({
  userId,
  token,
  onTimelineListStart,
}: {
  userId: number;
  token: string | null;
  onTimelineListStart?: () => void;
}) {
  const [user, setUser] = useState<User | null>(null);
  const [timeline, setTimeline] = useState<Timeline[] | null>(null);
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [biography, setBiography] = useState<string>('');
  const [isEditing, setIsEditing] = useState(false);
  const [editedBiography, setEditedBiography] = useState<string>('');
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    fetchData();
  }, [userId, token]);

  const fetchData = async () => {
    try {
      const apiUrl = API_URL;
      if (!apiUrl) throw new Error('API URLが設定されていません');

      console.log('📖 データ取得開始...');
      console.log('🔑 userId:', userId, 'token:', token?.substring(0, 20) + '...');

      // ステップ1: ユーザー情報取得
      const userResponse = await fetch(`${apiUrl}/api/users/${userId}`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (!userResponse.ok) {
        throw new Error('ユーザー情報取得に失敗しました');
      }

      const userData = await userResponse.json();
      setUser(userData);
      console.log('✅ ユーザー情報取得完了:', userData);

      // ステップ2: タイムラインデータ取得
      const timelineUrl = `${apiUrl}/api/timeline?autoGenerated=true`;
      const timelineResponse = await fetch(timelineUrl, {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (!timelineResponse.ok) {
        throw new Error('タイムラインデータ取得に失敗しました');
      }

      let timelineDataArray: any[] = [];
      try {
        const responseText = await timelineResponse.text();
        timelineDataArray = JSON.parse(responseText);

        if (!Array.isArray(timelineDataArray)) {
          timelineDataArray = [timelineDataArray];
        }

        console.log('✅ タイムラインデータ取得完了:', timelineDataArray.length, '件');
      } catch (parseError: any) {
        throw new Error(`タイムラインデータのパースに失敗しました: ${parseError.message}`);
      }

      if (timelineDataArray.length === 0) {
        setError('AI生成人生記録がまだありません。聞き取りを完了してAI生成を実行してください。');
        setLoading(false);
        return;
      }

      setTimeline(timelineDataArray as Timeline[]);

      // ステップ3: 自分史データ取得
      const bioResponse = await fetch(`${apiUrl}/api/biography/${userId}`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (bioResponse.ok) {
        const bioData = await bioResponse.json();
        const bioText = bioData.edited_content || bioData.biography || '';
        setBiography(bioText);
        setEditedBiography(bioText);
        console.log('✅ 自分史データ取得完了');
      }

      // ステップ4: 写真データ取得
      if (timelineDataArray.length > 0 && timelineDataArray[0].id) {
        const photoResponse = await fetch(
          `${apiUrl}/api/timeline/${timelineDataArray[0].id}/photos`,
          { headers: { 'Authorization': `Bearer ${token}` } }
        );

        if (photoResponse.ok) {
          const photoData = await photoResponse.json();
          setPhotos(photoData);
          console.log('✅ 写真取得完了:', photoData.length, '枚');
        }
      }

      setLoading(false);
    } catch (error) {
      console.error('❌ データ取得エラー:', error);
      const errorMessage = error instanceof Error ? error.message : 'データ取得に失敗しました';
      setError(errorMessage);
      setLoading(false);
    }
  };

  const handleSaveBiography = async () => {
    if (!editedBiography.trim()) {
      alert('自分史の内容を入力してください');
      return;
    }

    setIsSaving(true);
    try {
      const apiUrl = API_URL;

      console.log('💾 修正内容を保存開始:', {
        userId,
        contentLength: editedBiography.length,
        timestamp: new Date().toISOString()
      });

      // ✅ 修正：/api/biography (POST) を使用
      // biography.ts の POST エンドポイントは user_id で biography を自動作成・更新
      const response = await fetch(`${apiUrl}/api/biography`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          edited_content: editedBiography,
          ai_summary: editedBiography  // ✅ ai_summary も設定
        }),
      });

      console.log('📡 サーバーレスポンス:', {
        status: response.status,
        statusText: response.statusText
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(`保存に失敗しました (${response.status}): ${errorData.error || 'Unknown error'}`);
      }

      const result = await response.json();
      console.log('✅ サーバー保存成功:', result);

      // ✅ 保存後、画面を再度読み込んでDBから最新データを取得
      // これにより確実にDBの最新データが表示される
      setBiography(editedBiography);
      setIsEditing(false);
      
      // ✅ 成功メッセージを表示
      alert('✅ 修正内容を保存しました');
      
      // ✅ 1秒後に全データを再読み込み（確実性を高める）
      setTimeout(() => {
        fetchData();
      }, 1000);

    } catch (err) {
      console.error('❌ 修正内容の保存エラー:', err);
      const errorMessage = err instanceof Error ? err.message : '予期しないエラーが発生しました';
      alert(`修正内容の保存に失敗しました:\n${errorMessage}\n\nもう一度お試しください。`);
    } finally {
      setIsSaving(false);
    }
  };

  const styles = {
    container: {
      maxWidth: '900px',
      margin: '0 auto',
      padding: '20px',
      backgroundColor: '#f8f9fa',
      minHeight: '100vh',
    } as const,
    header: {
      textAlign: 'center' as const,
      marginBottom: '30px',
    } as const,
    title: {
      fontSize: '28px',
      color: '#2c3e50',
      marginBottom: '10px',
    } as const,
    subtitle: {
      fontSize: '14px',
      color: '#7f8c8d',
    } as const,
    card: {
      backgroundColor: 'white',
      padding: '20px',
      marginBottom: '20px',
      borderRadius: '8px',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    } as const,
    sectionTitle: {
      fontSize: '18px',
      color: '#2c3e50',
      marginBottom: '15px',
      marginTop: '0',
    } as const,
    button: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '4px',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    } as const,
    loadingBox: {
      padding: '20px',
      textAlign: 'center' as const,
      color: '#7f8c8d',
    } as const,
    errorBox: {
      padding: '15px',
      backgroundColor: '#f8d7da',
      border: '1px solid #f5c6cb',
      borderRadius: '4px',
      color: '#721c24',
      marginBottom: '15px',
    } as const,
    content: {
      padding: '15px',
      backgroundColor: '#f9f9f9',
      borderRadius: '4px',
      marginBottom: '15px',
      whiteSpace: 'pre-wrap' as const,
      wordWrap: 'break-word' as const,
      lineHeight: '1.6',
    } as const,
    bioDisplay: {
      padding: '15px',
      backgroundColor: '#f9f9f9',
      borderRadius: '4px',
      border: '1px solid #ecf0f1',
      marginBottom: '15px',
      minHeight: '200px',
      whiteSpace: 'pre-wrap' as const,
      wordWrap: 'break-word' as const,
    } as const,
    yearTable: {
      width: '100%',
      borderCollapse: 'collapse' as const,
      marginBottom: '20px',
    } as const,
    tableHeader: {
      backgroundColor: '#34495e',
      color: 'white',
      padding: '10px',
      textAlign: 'left' as const,
      fontSize: '13px',
    } as const,
    tableCell: {
      padding: '10px',
      borderBottom: '1px solid #ecf0f1',
      fontSize: '13px',
    } as const,
    photoGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '15px',
      marginTop: '15px',
    } as const,
    photoCard: {
      borderRadius: '8px',
      overflow: 'hidden' as const,
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    } as const,
    photoImage: {
      width: '100%',
      height: 'auto',
      display: 'block',
    } as const,
  };

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.loadingBox}>⏳ データを読み込み中...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>⚠️ エラー</h1>
        </div>
        <div style={styles.card}>
          <div style={styles.errorBox}>
            <strong>エラー内容:</strong>
            <p>{error}</p>
          </div>
          <button
            style={{ ...styles.button, backgroundColor: '#3498db', color: 'white' }}
            onClick={() => window.location.reload()}
          >
            🔄 再度読み込む
          </button>
        </div>
      </div>
    );
  }

  if (!timeline || timeline.length === 0) {
    return (
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>📖 わたしの自分史</h1>
        </div>
        <div style={styles.card}>
          <p>データがまだ準備できていません。</p>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h1 style={styles.title}>📖 修正済みテキスト確認</h1>
        <p style={styles.subtitle}>
          {user?.name || '（名前未設定）'}さん - {user?.age}歳
        </p>
      </div>

      {/* 自分史テキスト確認・修正 */}
      <div style={styles.card}>
        <h2 style={styles.sectionTitle}>📝 あなたの自分史</h2>

        {!isEditing ? (
          <>
            <div style={styles.bioDisplay}>{biography}</div>
            <button
              onClick={() => {
                setIsEditing(true);
                setEditedBiography(biography);
              }}
              style={{
                ...styles.button,
                backgroundColor: '#3498db',
                color: 'white',
                marginBottom: '15px',
              }}
            >
              ✏️ 修正する
            </button>
          </>
        ) : (
          <>
            <textarea
              value={editedBiography}
              onChange={(e) => setEditedBiography(e.target.value)}
              style={{
                width: '100%',
                minHeight: '300px',
                padding: '15px',
                fontSize: '15px',
                border: '1px solid #bdc3c7',
                borderRadius: '4px',
                marginBottom: '15px',
                fontFamily: 'inherit',
              }}
            />
            <div style={{ display: 'flex', gap: '10px', marginBottom: '15px' }}>
              <button
                onClick={handleSaveBiography}
                disabled={isSaving}
                style={{
                  ...styles.button,
                  backgroundColor: '#27ae60',
                  color: 'white',
                  flex: 1,
                  opacity: isSaving ? 0.6 : 1,
                }}
              >
                {isSaving ? '保存中...' : '✅ 修正内容を保存'}
              </button>
              <button
                onClick={() => setIsEditing(false)}
                style={{
                  ...styles.button,
                  backgroundColor: '#95a5a6',
                  color: 'white',
                  flex: 1,
                }}
              >
                ❌ キャンセル
              </button>
            </div>
          </>
        )}
      </div>

      {/* タイムラインカード */}
      {timeline.map((timelineItem, index) => (
        <div key={timelineItem.id} style={styles.card}>
          <h2 style={styles.sectionTitle}>📖 自分史 - Part {index + 1}</h2>

          {(timelineItem.edited_content || timelineItem.event_description) && (
            <div style={styles.content}>
              {timelineItem.edited_content || timelineItem.event_description}
            </div>
          )}

          {index === 0 && photos.length > 0 && (
            <div>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', color: '#2c3e50', marginBottom: '15px' }}>
                📷 思い出の写真
              </h3>
              <div style={styles.photoGrid}>
                {photos.map((photo) => (
                  <div key={photo.id} style={styles.photoCard}>
                    <img
                      src={`${API_URL}${photo.file_path}`}
                      alt="思い出"
                      style={styles.photoImage}
                      onError={(e) => {
                        (e.target as HTMLImageElement).src =
                          'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22200%22 height=%22150%22%3E%3Crect fill=%22%23ddd%22 width=%22200%22 height=%22150%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 dominant-baseline=%22middle%22 text-anchor=%22middle%22 font-family=%22Arial%22 font-size=%2214%22 fill=%22%23999%22%3E画像読込エラー%3C/text%3E%3C/svg%3E';
                      }}
                    />
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ))}

      {/* 人生年表 */}
      <div style={styles.card}>
        <h2 style={styles.sectionTitle}>📊 人生年表</h2>
        <table style={styles.yearTable}>
          <thead>
            <tr>
              <th style={{ ...styles.tableHeader, width: '15%', textAlign: 'center' }}>年</th>
              <th style={{ ...styles.tableHeader, width: '10%', textAlign: 'center' }}>月</th>
              <th style={{ ...styles.tableHeader, width: '75%' }}>できごと</th>
            </tr>
          </thead>
          <tbody>
            {timeline.map((timelineItem) => (
              <tr key={timelineItem.id}>
                <td style={{ ...styles.tableCell, textAlign: 'center' }}>
                  {timelineItem.year ? timelineItem.year.toString() : '-'}
                </td>
                <td style={{ ...styles.tableCell, textAlign: 'center' }}>
                  {timelineItem.month ? timelineItem.month.toString() : '-'}
                </td>
                <td style={styles.tableCell}>
                  {timelineItem.edited_content
                    ? timelineItem.edited_content.substring(0, 100) +
                      (timelineItem.edited_content.length > 100 ? '...' : '')
                    : timelineItem.event_description
                    ? timelineItem.event_description.substring(0, 100) +
                      (timelineItem.event_description.length > 100 ? '...' : '')
                    : timelineItem.event_title || '（内容なし）'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 次へボタン */}
      {!isEditing && (
        <button
          onClick={() => {
            if (onTimelineListStart) {
              console.log('📋 TimelineListPage へ遷移');
              onTimelineListStart();
            }
          }}
          style={{
            ...styles.button,
            backgroundColor: '#e74c3c',
            color: 'white',
            width: '100%',
            marginBottom: '15px',
            fontSize: '16px',
            fontWeight: 'bold',
          }}
        >
          📅 人生年表を作成 →
        </button>
      )}
    </div>
  );
}
