import { useState, useEffect } from 'react';
import { API_URL } from '../config';

// ✅ 修正: Timeline を配列対応に
interface Timeline {
  id: number;
  year: number | null;
  month: number | null;
  event_title: string;
  event_description: string;
  edited_content: string;
  turning_point: string;
  created_at: string;
  is_auto_generated: number;
}

interface Photo {
  id: number;
  file_path: string;
  description: string;
}

interface User {
  id: number;
  name: string;
  age: number;
}

export default function CorrectedTextPage({ userId, token }: { userId: number; token: string | null }) {
  const [user, setUser] = useState<User | null>(null);
  // ✅ 修正: timeline を配列に変更
  const [timeline, setTimeline] = useState<Timeline[] | null>(null);
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pdfGenerating, setPdfGenerating] = useState(false);

  useEffect(() => {
    fetchData();
  }, [userId, token]);

  const fetchData = async () => {
    try {
      const apiUrl = API_URL;
      if (!apiUrl) throw new Error('API URLが設定されていません');

      console.log('📖 データ取得開始...');
      console.log('🔑 userId:', userId, 'token:', token?.substring(0, 20) + '...');

      // ステップ1: ユーザー情報取得
      console.log('👤 ユーザー情報を取得...');
      const userResponse = await fetch(`${apiUrl}/api/users/${userId}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (!userResponse.ok) {
        throw new Error('ユーザー情報取得に失敗しました');
      }

      const userData = await userResponse.json();
      setUser(userData);
      console.log('✅ ユーザー情報取得完了:', userData);

      // ステップ2: ✅ 修正 - タイムラインデータ取得（すべて取得）
      console.log('🤖 タイムラインデータを取得...');
      const timelineUrl = `${apiUrl}/api/timeline?autoGenerated=true`;
      console.log('📡 リクエストURL:', timelineUrl);

      const timelineResponse = await fetch(timelineUrl, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (!timelineResponse.ok) {
        throw new Error(`タイムラインデータ取得に失敗しました: ${timelineResponse.status}`);
      }

      const timelineDataArray = await timelineResponse.json();
      console.log('✅ タイムラインデータ取得完了:', timelineDataArray);
      console.log('📊 取得件数:', timelineDataArray.length);

      if (timelineDataArray.length === 0) {
        console.warn('⚠️ AI生成人生記録がありません');
        setError('AI生成人生記録がまだありません。聞き取りを完了してAI生成を実行してください。');
        setLoading(false);
        return;
      }

      // ✅ 修正: すべてのタイムラインを配列として保存
      setTimeline(timelineDataArray as Timeline[]);

      // ステップ3: 写真データ取得（最初のタイムラインの写真のみ取得）
      if (timelineDataArray.length > 0 && timelineDataArray[0].id) {
        console.log('🖼️ 写真を取得...');
        const photoResponse = await fetch(`${apiUrl}/api/timeline/${timelineDataArray[0].id}/photos`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        if (photoResponse.ok) {
          const photoData = await photoResponse.json();
          console.log('✅ 写真取得完了:', photoData.length, '枚');
          setPhotos(photoData);
        } else {
          console.warn('⚠️ 写真取得に失敗しました');
        }
      }

      setLoading(false);
    } catch (error) {
      console.error('❌ データ取得エラー:', error);
      const errorMessage = error instanceof Error ? error.message : 'データ取得に失敗しました';
      setError(errorMessage);
      setLoading(false);
    }
  };

  const generatePDF = async () => {
    try {
      setPdfGenerating(true);

      const apiUrl = API_URL;
      if (!apiUrl) throw new Error('API URLが設定されていません');

      console.log('📄 PDF生成リクエスト送信...');
      const response = await fetch(`${apiUrl}/api/pdf/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({})
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'PDF生成に失敗しました');
      }

      const data = await response.json();
      console.log('✅ PDF生成完了:', data);

      // ✅ PDFをダウンロード
      const downloadUrl = `${apiUrl}${data.filepath}`;
      console.log('📥 ダウンロードURL:', downloadUrl);

      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = data.filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);

      alert('✅ PDFをダウンロードしました！');
      setPdfGenerating(false);
    } catch (error) {
      console.error('❌ PDF生成エラー:', error);
      const errorMessage = error instanceof Error ? error.message : 'PDF生成に失敗しました';
      alert(`❌ エラー: ${errorMessage}`);
      setPdfGenerating(false);
    }
  };

  const styles = {
    container: {
      maxWidth: '900px',
      margin: '0 auto',
      padding: '20px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif',
    },
    header: {
      textAlign: 'center' as const,
      marginBottom: '30px',
    },
    title: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: '#2c3e50',
      marginBottom: '10px',
    },
    subtitle: {
      fontSize: '14px',
      color: '#7f8c8d',
    },
    card: {
      backgroundColor: 'white',
      padding: '20px',
      borderRadius: '8px',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
      marginBottom: '20px',
    },
    sectionTitle: {
      fontSize: '18px',
      fontWeight: 'bold',
      color: '#2c3e50',
      marginBottom: '15px',
      borderBottom: '2px solid #3498db',
      paddingBottom: '10px',
    },
    content: {
      fontSize: '15px',
      color: '#34495e',
      lineHeight: '1.8',
      marginBottom: '20px',
      whiteSpace: 'pre-wrap' as const,
      wordWrap: 'break-word' as const,
    },
    photoGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: '15px',
      marginBottom: '20px',
    },
    photoCard: {
      borderRadius: '8px',
      overflow: 'hidden',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    photoImage: {
      width: '100%',
      height: '150px',
      objectFit: 'cover' as const,
    },
    photoDescription: {
      padding: '10px',
      backgroundColor: '#f8f9fa',
      fontSize: '12px',
      color: '#7f8c8d',
    },
    yearTable: {
      width: '100%',
      borderCollapse: 'collapse' as const,
      marginTop: '15px',
    },
    tableHeader: {
      backgroundColor: '#ecf0f1',
      padding: '10px',
      fontWeight: 'bold',
      color: '#2c3e50',
      borderBottom: '2px solid #bdc3c7',
    },
    tableCell: {
      padding: '10px',
      borderBottom: '1px solid #ecf0f1',
      color: '#34495e',
    },
    button: {
      padding: '12px 30px',
      fontSize: '16px',
      borderRadius: '8px',
      border: 'none',
      cursor: 'pointer',
      fontWeight: '600',
      transition: 'all 0.3s ease',
    },
    downloadButton: {
      backgroundColor: '#27ae60',
      color: 'white',
      width: '100%',
      minHeight: '48px',
    },
    downloadButtonDisabled: {
      backgroundColor: '#95a5a6',
      cursor: 'not-allowed',
      opacity: 0.6,
    },
    errorBox: {
      backgroundColor: '#ffebee',
      color: '#c62828',
      padding: '20px',
      borderRadius: '4px',
      marginBottom: '20px',
    },
    loadingBox: {
      textAlign: 'center' as const,
      padding: '40px',
      fontSize: '16px',
      color: '#7f8c8d',
    },
  };

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.loadingBox}>
          ⏳ データを読み込み中...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>⚠️ エラー</h1>
        </div>
        <div style={styles.card}>
          <div style={styles.errorBox}>
            <strong>エラー内容:</strong>
            <p>{error}</p>
          </div>
          <button
            style={styles.button}
            onClick={() => window.location.reload()}
          >
            🔄 再度読み込む
          </button>
        </div>
      </div>
    );
  }

  if (!timeline || timeline.length === 0) {
    return (
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>📖 わたしの自分史</h1>
        </div>
        <div style={styles.card}>
          <p>データがまだ準備できていません。</p>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h1 style={styles.title}>📖 わたしの自分史</h1>
        <p style={styles.subtitle}>{user?.name || '（名前未設定）'}さん - {user?.age}歳</p>
      </div>

      {/* ✅ 修正: 複数のタイムラインを表示 */}
      {timeline.map((timelineItem, index) => (
        <div key={timelineItem.id} style={styles.card}>
          <h2 style={styles.sectionTitle}>
            📖 自分史 - Part {index + 1}
          </h2>

          {/* コンテンツ表示 */}
          {(timelineItem.edited_content || timelineItem.event_description) && (
            <div style={styles.content}>
              {timelineItem.edited_content || timelineItem.event_description}
            </div>
          )}

          {/* 年月表示 */}
          {(timelineItem.year || timelineItem.month) && (
            <div style={{ marginBottom: '15px', fontSize: '14px', color: '#7f8c8d' }}>
              📅 {timelineItem.year && `${timelineItem.year}年`}
              {timelineItem.month && `${timelineItem.month}月`}
              {!timelineItem.year && !timelineItem.month && '日時未記入'}
            </div>
          )}

          {/* 写真表示（最初のタイムラインの場合のみ） */}
          {index === 0 && photos.length > 0 && (
            <div>
              <h3 style={{
                fontSize: '16px',
                fontWeight: 'bold',
                color: '#2c3e50',
                marginBottom: '15px',
              }}>
                📷 思い出の写真
              </h3>
              <div style={styles.photoGrid}>
                {photos.map((photo) => (
                  <div key={photo.id} style={styles.photoCard}>
                    <img
                      src={`${API_URL}${photo.file_path}`}
                      alt="思い出"
                      style={styles.photoImage}
                      onError={(e) => {
                        (e.target as HTMLImageElement).src = 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22200%22 height=%22150%22%3E%3Crect fill=%22%23ddd%22 width=%22200%22 height=%22150%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 dominant-baseline=%22middle%22 text-anchor=%22middle%22 font-family=%22Arial%22 font-size=%2214%22 fill=%22%23999%22%3E画像読込エラー%3C/text%3E%3C/svg%3E';
                      }}
                    />
                    {photo.description && (
                      <div style={styles.photoDescription}>
                        {photo.description}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ))}

      {/* ✅ 修正: 年表セクション - 複数行表示 */}
      <div style={styles.card}>
        <h2 style={styles.sectionTitle}>📊 人生年表</h2>
        <table style={styles.yearTable}>
          <thead>
            <tr>
              <th style={{ ...styles.tableHeader, width: '15%', textAlign: 'center' }}>年</th>
              <th style={{ ...styles.tableHeader, width: '10%', textAlign: 'center' }}>月</th>
              <th style={{ ...styles.tableHeader, width: '75%' }}>できごと</th>
            </tr>
          </thead>
          <tbody>
            {/* ✅ すべてのタイムラインを行として表示 */}
            {timeline.map((timelineItem) => (
              <tr key={timelineItem.id}>
                <td style={{ ...styles.tableCell, textAlign: 'center' }}>
                  {timelineItem.year ? timelineItem.year.toString() : '-'}
                </td>
                <td style={{ ...styles.tableCell, textAlign: 'center' }}>
                  {timelineItem.month ? timelineItem.month.toString() : '-'}
                </td>
                <td style={styles.tableCell}>
                  {timelineItem.edited_content
                    ? timelineItem.edited_content.substring(0, 100) + (timelineItem.edited_content.length > 100 ? '...' : '')
                    : timelineItem.event_description
                    ? timelineItem.event_description.substring(0, 100) + (timelineItem.event_description.length > 100 ? '...' : '')
                    : timelineItem.event_title || '（内容なし）'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* PDF生成ボタン */}
      <button
        onClick={generatePDF}
        disabled={pdfGenerating}
        style={{
          ...styles.button,
          ...styles.downloadButton,
          ...(pdfGenerating ? styles.downloadButtonDisabled : {}),
        }}
      >
        {pdfGenerating ? '📄 PDF生成中...' : '📄 PDFをダウンロード'}
      </button>
    </div>
  );
}
